language: ruby
bundler_args: "--without debug production"
cache: bundler
rvm:
- 2.6.3
notifications:
  email:
    recipients:
    - sylvester@keil.or.atx
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: Rkau0ab7IRDQvdEe+8o3bubDPRHJogADO1NBWJLUNsq0cGqJxWRXqWCpszMbDW++B62Fn7b95vMhRtGVyPRd0H5moPs/iJTQM0P3RtNn0pAibSH1PPEAEyE+Wkv3Fqq+Sy3pOd+I249l+yJ/HcHahQZYL0Lxr0AEss7prOvHZ3U=
  app: shelbot
  on:
    repo: citation-style-language/Sheldon
